logging-config:
    version: 1
    disable_existing_loggers: False

    formatters:
        default:
            format: '[%(asctime)s] %(levelname)s in %(module)s: %(message)s'

    handlers:
        wsgi:
            class: logging.StreamHandler
            level: INFO
            formatter: default

        time-rotate:
            class: logging.handlers.TimedRotatingFileHandler
            level: INFO
            formatter: default
            filename: './logs/app.log'
            when: 'M'
            interval: 10
            backupCount: 5
            delay: False
            encoding: utf-8

    root:
        level: INFO
        handlers: ['wsgi', 'time-rotate']

database:
    url: 'mysql://root:%s@localhost:3306/hrb2'
    password: 'Abcd@1234'