# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpclib/useraccount.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19grpclib/useraccount.proto\x12\x0buseraccount\"\x18\n\x06UserId\x12\x0e\n\x06UserId\x18\x01 \x01(\x05\"J\n\x04User\x12\x0e\n\x06UserId\x18\x01 \x01(\x05\x12\x11\n\tFirstName\x18\x02 \x01(\t\x12\x10\n\x08LastName\x18\x03 \x01(\t\x12\r\n\x05\x45mail\x18\x04 \x01(\t\"Y\n\x11\x43reateUserRequest\x12\x11\n\tFirstName\x18\x01 \x01(\t\x12\x10\n\x08LastName\x18\x02 \x01(\t\x12\r\n\x05\x45mail\x18\x03 \x01(\t\x12\x10\n\x08Password\x18\x04 \x01(\t\"3\n\x10LoginUserRequest\x12\r\n\x05\x45mail\x18\x01 \x01(\t\x12\x10\n\x08Password\x18\x02 \x01(\t\"G\n\x11LoginUserResponse\x12\x11\n\tIsSuccess\x18\x01 \x01(\x08\x12\x1f\n\x04User\x18\x02 \x01(\x0b\x32\x11.useraccount.User\"9\n\x15UpdatePasswordRequest\x12\x0e\n\x06UserId\x18\x01 \x01(\x05\x12\x10\n\x08Password\x18\x02 \x01(\t\"L\n\x16UpdatePasswordResponse\x12\x11\n\tIsSuccess\x18\x01 \x01(\x08\x12\x1f\n\x04User\x18\x02 \x01(\x0b\x32\x11.useraccount.User2\xb0\x02\n\x0bUserAccount\x12\x33\n\x07GetUser\x12\x13.useraccount.UserId\x1a\x11.useraccount.User\"\x00\x12\x41\n\nCreateUser\x12\x1e.useraccount.CreateUserRequest\x1a\x11.useraccount.User\"\x00\x12L\n\tLoginUser\x12\x1d.useraccount.LoginUserRequest\x1a\x1e.useraccount.LoginUserResponse\"\x00\x12[\n\x0eUpdatePassword\x12\".useraccount.UpdatePasswordRequest\x1a#.useraccount.UpdatePasswordResponse\"\x00\x42&\n\x0buseraccountB\x10UserAccountProtoP\x01\xa2\x02\x02UAb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpclib.useraccount_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013useraccountB\020UserAccountProtoP\001\242\002\002UA'
  _globals['_USERID']._serialized_start=42
  _globals['_USERID']._serialized_end=66
  _globals['_USER']._serialized_start=68
  _globals['_USER']._serialized_end=142
  _globals['_CREATEUSERREQUEST']._serialized_start=144
  _globals['_CREATEUSERREQUEST']._serialized_end=233
  _globals['_LOGINUSERREQUEST']._serialized_start=235
  _globals['_LOGINUSERREQUEST']._serialized_end=286
  _globals['_LOGINUSERRESPONSE']._serialized_start=288
  _globals['_LOGINUSERRESPONSE']._serialized_end=359
  _globals['_UPDATEPASSWORDREQUEST']._serialized_start=361
  _globals['_UPDATEPASSWORDREQUEST']._serialized_end=418
  _globals['_UPDATEPASSWORDRESPONSE']._serialized_start=420
  _globals['_UPDATEPASSWORDRESPONSE']._serialized_end=496
  _globals['_USERACCOUNT']._serialized_start=499
  _globals['_USERACCOUNT']._serialized_end=803
# @@protoc_insertion_point(module_scope)
